### ISSUE TITLE
Bug with number of pages

### ISSUE THREAD

**Issue by Escabou** [CodeStix/scoplayer-to-pdf#2]
Sometimes there are less pages and sometimes there are more. Not sure where those pages are when I take a quick glance at it, it's especially noticeable with 200+ pages.
Thanks again for this tool!

**Comment by CodeStix** [comment]
Pages were skipped when one of the page layers (solution layer / normal layer) could not be resolved, this is an issue because not all pages have a solution layer. Should be fixed. 
Glad you like it!
